### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by dbFlower** [Last-Order/DDTest#1]
1 手机端适配
2 音频选项， 选择结束后音频仍在播放

**Comment by Last-Order** [comment]
已确认

**Comment by kingfree** [comment]
1. 你可以加个多语言放推特上虐下日本阿宅
2. 刚才群里讨论的，可以扒Hosi_Tiri的微博，甚至可以搞个多选

**Comment by Last-Order** [comment]
@kingfree 多语言这个可以有。微博那个我也有看，感觉不好扒，比如多个tag对应多张图什么的。
